# Schema for the configuration files of the Custom configuration module.
custom_configuration.settings:
  type: config_object
  label: 'Custom configuration settings'
  mapping:
    example:
      type: string
      label: 'Example'
